In [1]:
#Clean financial datasets by handling missing values, removing duplicate records, correcting inconsistent entries,
#and preparing accurate datasets for business analysis using Pandas.

In [43]:
import pandas as pd

In [44]:
df=pd.read_csv("financial_dataset.csv")

In [45]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [46]:
df.head(2)

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00

In [47]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Customer_Name        0
Category            23
Sales               33
Profit              30
Quantity             0
Payment_Status       0
City                21
Transaction_Date     0
dtype: int64

In [48]:
df["Sales"]=df["Sales"].fillna(df["Sales"].mean())

In [49]:
df["Profit"]=df["Profit"].fillna(df["Profit"].mean())

In [50]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [51]:
df["City"]=df["City"].fillna(df["City"].mode()[0])

In [52]:
df.duplicated().sum()

np.int64(40)

In [53]:
df=df.drop_duplicates()

In [54]:
df["Category"]=df["Category"].str.strip().str.title()

C:\Users\Admin\AppData\Local\Temp\ipykernel_5732\3960893055.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"]=df["Category"].str.strip().str.title()

In [55]:
df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

C:\Users\Admin\AppData\Local\Temp\ipykernel_5732\1034170163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

In [56]:
df["City"]=df["City"].str.strip().str.title()

C:\Users\Admin\AppData\Local\Temp\ipykernel_5732\3137970100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"]=df["City"].str.strip().str.title()

In [59]:
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"], errors="coerce")
df.dtypes

C:\Users\Admin\AppData\Local\Temp\ipykernel_5732\2971976620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"], errors="coerce")

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [58]:
print("Cleaned Financial Dataset:")
df

Cleaned Financial Dataset:

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [61]:
df.to_csv("cleaned_financial_transactions.csv")

In [62]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00